name: Deploy Develop with APK

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-attach:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Build Android APK
        id: apk-build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          mkdir -p build-artifacts
          eas build \
            --platform android \
            --profile preview \
            --non-interactive \
            --local \
            --output build-artifacts/app-preview.apk
          echo "apk-path=build-artifacts/app-preview.apk" >> $GITHUB_OUTPUT

      - name: Validate APK
        run: |
          if [ ! -f "build-artifacts/app-preview.apk" ]; then
            echo "::error::Build failed - APK not found"
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-preview
          path: build-artifacts/app-preview.apk
          retention-days: 1

      - name: Post PR comment
        uses: actions/github-script@v6
        with:
          script: |
            const apkSize = require('fs').statSync('build-artifacts/app-preview.apk').size / (1024 * 1024);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
                ### 📲 APK Build Successful!

                **Download**: [APK Artifact](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID})

                **Build Details**:
                - File Size: ${apkSize.toFixed(2)} MB
                - Generated: ${new Date().toUTCString()}
              `
            });
