name: Deploy Develop with APK

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-attach:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Build Android APK Locally
        id: build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          mkdir -p ./build-artifacts
          eas build --platform android --profile preview --non-interactive --local --output ./build-artifacts/
          APK_PATH=$(ls ./build-artifacts/*.apk)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_OUTPUT
          echo "APK path: $APK_PATH"

      - name: Validate APK exists
        run: |
          if [ ! -f "${{ steps.build.outputs.APK_PATH }}" ]; then
            echo "::error::APK file not found at ${{ steps.build.outputs.APK_PATH }}"
            exit 1
          fi

      - name: Upload APK as Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-preview
          path: ${{ steps.build.outputs.APK_PATH }}

      - name: Comment on PR with APK
        if: success()
        uses: actions/github-script@v6
        env:
          APK_PATH: ${{ steps.build.outputs.APK_PATH }}
        with:
          script: |
            const fs = require('fs');
            const { context } = require('@actions/github');
            const core = require('@actions/core');
            
            const apkPath = process.env.APK_PATH;
            if (!fs.existsSync(apkPath)) {
              core.setFailed(`APK not found at ${apkPath}`);
              return;
            }

            const apkContent = fs.readFileSync(apkPath, { encoding: 'base64' });
            const commentBody = `
              ### 🚀 APK for Testing

              A new APK has been built for this PR. You can download it below:

              📥 **Download APK**: [app-preview.apk](data:application/vnd.android.package-archive;base64,${apkContent})

              ---

              **Note**: This is a test build. Report any issues in the comments.
            `;

            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody,
              });
            } catch (error) {
              core.error(`Failed to create comment: ${error.message}`);
            }